{
    "@context":"https://schema.org",
    "@graph":[
        {
            "@type":"WebPage",
            "@id":"https://vhnm.in/",
            "url":"https://vhnm.in/",
            "name":"Discover Best Oversized Sweat Shirts & Hoodies Online VHNM",
            "isPartOf":{"@id":"https://vhnm.in/#website"},
            "about":{"@id":"https://vhnm.in/#organization"},
            "primaryImageOfPage":{"@id":"https://vhnm.in/#primaryimage"},
            "image":{"@id":"https://vhnm.in/#primaryimage"},
            "thumbnailUrl":"https://vhnm.in/wp-content/uploads/2023/12/Babu-BhaiyaUK07-Rider-In-VHNM-Hoodie-scaled.jpg",
            "datePublished":"2023-12-02T07:35:35+00:00",
            "dateModified":"2023-12-15T12:32:40+00:00",
            "description":"Discover the latest men's fashion trends at VHNM India. Shop online for stylish clothing, including Oversized Sweat Shirts & Hoodies Online.",
            "breadcrumb":{"@id":"https://vhnm.in/#breadcrumb"},
            "inLanguage":"en-US",
            "potentialAction":[
                {
                    "@type":"ReadAction",
                    "target":["https://vhnm.in/"]
                }
            ]
        },
        {
            "@type":"ImageObject",
            "inLanguage":"en-US",
            "@id":"https://vhnm.in/#primaryimage",
            "url":"https://vhnm.in/wp-content/uploads/2023/12/Babu-BhaiyaUK07-Rider-In-VHNM-Hoodie-scaled.jpg",
            "contentUrl":"https://vhnm.in/wp-content/uploads/2023/12/Babu-BhaiyaUK07-Rider-In-VHNM-Hoodie-scaled.jpg",
            "width":2560,"height":1280
        },
        {
            "@type":"BreadcrumbList",
            "@id":"https://vhnm.in/#breadcrumb",
            "itemListElement":[
                {
                    "@type":"ListItem",
                    "position":1,
                    "name":"Home"
                }
            ]
        },
        {
            "@type":"WebSite",
            "@id":"https://vhnm.in/#website",
            "url":"https://vhnm.in/",
            "name":"VHNM",
            "description":"",
            "publisher":{"@id":"https://vhnm.in/#organization"},
            "potentialAction":[
                {
                    "@type":"SearchAction",
                    "target":{
                        "@type":"EntryPoint",
                        "urlTemplate":"https://vhnm.in/?s={search_term_string}"
                    },
                    "query-input":"required name=search_term_string"
                }],
            "inLanguage":"en-US"
        },
        {
            "@type":"Organization",
            "@id":"https://vhnm.in/#organization",
            "name":"VHNM",
            "url":"https://vhnm.in/",
            "logo":{
                "@type":"ImageObject",
                "inLanguage":"en-US",
                "@id":"https://vhnm.in/#/schema/logo/image/",
                "url":"https://vhnm.in/wp-content/uploads/2023/09/VHNM-logo.png",
                "contentUrl":"https://vhnm.in/wp-content/uploads/2023/09/VHNM-logo.png",
                "width":1548,
                "height":620,
                "caption":"VHNM"
            },
            "image":{
                "@id":"https://vhnm.in/#/schema/logo/image/"
            },
            "sameAs":["https://www.instagram.com/vhnm.in/"]
        }
    ]
}